### ISSUE TITLE
Occasionally stops speed tanking

### ISSUE THREAD

**Issue by below0isk** [Da-Teach/Questor#104]
Build: 10th Dec. Master
Speedtank is on with range set.

it looks like questor stops orbiting a current target. after manually order to orbit a target the questor routine is back and orbits for the rest of the mission.
encountered this in The Blockade. Maybe of extensive dampening. will follow this issue for varification in other missions.

**Comment by below0isk** [comment]
both on EXPERIMENTAL and MASTER since 10th dec questor release.

**Comment by ISeeDEDPpl** [comment]
Could you test my branch and see if it resolves the issues you were seeing? I disabled all wreck opening unless we are processing a loot action. The theory being that CCP added an approach on open if the wreck moves out of range, breaking the orbit. 

https://github.com/ISeeDEDPpl/Questor/commits/experimental

**Comment by ISeeDEDPpl** [comment]
This issue should be resolved in both my tree and experimental.
