### ISSUE TITLE
red errors on EXP

### ISSUE THREAD

**Issue by Pluckyduck** [Da-Teach/Questor#107]
got 7 red errors with the new 28/29 Dec Exp build.

"Failed to delete key because it wasn't there"

just wanted to report this.

**Comment by rixim** [comment]
I need a lot more than that to do anything about it, but thanks for the
heads up. mention it in IRC and maybe we can work it out.

On Fri, Dec 30, 2011 at 11:59 AM, Pluckyduck <
reply@reply.github.com

**Comment by Pluckyduck** [comment]
rixim, going go close this as i was not able to reproduce it, i still have the log file if you would like to look at the lines
