### ISSUE TITLE
Directeve attempts to read/write protected memory

### ISSUE THREAD

**Issue by jhaskell** [Da-Teach/Questor#108]
I'm receiving this error when I run questor:

```
Exception during event execution: System.TypeInitializationException: The type initializer for
'.' threw an exception. ---> System.AccessViolationException: Attempted to read or write
protected memory. This is often an indication that other memory is corrupt.
   at ..()
   at ..()
   at ...ctor( , IntPtr , Boolean )
   at ...cctor()
   --- End of inner exception stack trace ---
   at ...ctor(Boolean )
   at DirectEve.DirectEve.(Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32
ThisObject)
```

I have received this error with two different machines -- my host machine (windows 7, x64, with UAC both on and off and running Innerspace and Eve as administrator), and a tinyxp virtual machine. The error is the same as https://github.com/Da-Teach/Questor/issues/100 , but reinstalling Innerspace did not solve the problem.

**Comment by fcrick** [comment]
when you say "when I run questor" do you mean when you first launch it?  Can you elaborate?

**Comment by jhaskell** [comment]
Ah, yes. I've successfully compiled questor and I'm in game, and running "dotnet questor" in the innerspace console. That error was taken from the innerspace console after questor failed to run.

**Comment by ISeeDEDPpl** [comment]
Can you duplicate this issue on a full install of Windows XP? TinyXP is quite likely missing a dependency. have you tried running dependency walker or similar to find out if something in your operating system is missing?
