### ISSUE TITLE
It doesn't use Mission.xml-> "Kill" and "Loot" 

### ISSUE THREAD

**Issue by Sko11** [Da-Teach/Questor#109]
The Pocket number is okay but when my ship arrived in the pocken (The damsel in distress) and should open fire and destroy the hub. It just clears the pocket and changes to gotobase stat. 
It doesn't loot mission objective also.

Version: 8cf59d2

Thanks in advance.

S.

**Comment by rixim** [comment]
This does not sound like an issue with questor, if it cannot be confirmed or repeated I am closing.

**Comment by Sko11** [comment]
Well.. I don't know what could create this kind of error then. You can close it if nobody experienced this problem except me.
Anyway. New build was released today. I will wait the update and try it again.
Have a nice day!
