### ISSUE TITLE
Bot warps to mission and stops

### ISSUE THREAD

**Issue by jakesmurf** [Da-Teach/Questor#11]
Just now I had the bot warp to a mission and then do nothing.  Unfortunately, I had looked away from the game for just a few minutes and when I came back I was in a capsule in station.  

As best I can tell from the ` log, it just shows that it warping to the mission bookmark
And then the capsule panic kicks in a couple minutes later
The killmail shows that the ship only sustained 30k damage (on a marauder), so the bot apparently never activated hardeners or the shield booster and just sat there and died (to 4 cruiser size enemies).  

From the combat logs, the bot never attempted to fight back.  I've been running the bot for several weeks now and have a good config, I've left it running unattending for 8ish hour stretches with no issues.  

I have no idea what else could have caused it.  I did not pause the bot or anything of that nature.  

It should be noted that I'm not complaining whatsoever, I just wanted you to be aware of the issue in case it's an artifact in the new questor build.

**Comment by rixim** [comment]
Thanks for the heads up.
