### ISSUE TITLE
Problem targeting wreck

### ISSUE THREAD

**Issue by freeaspx** [Da-Teach/Questor#110]
During loot questor doesn't target wreck.

**Comment by freeaspx** [comment]
The problem is the wreck owned by corp. If the character is part of corp npc the targeting is ok. Can you resolve this bug? Thanks

**Comment by ISeeDEDPpl** [comment]
no, it is not a good idea to loot other ppls wrecks where you do not have looting rights. You will be 'flagged'.

If you can describe a good reason this could possibly be made a setting, but as it stands I see no good reason to open yourself up to being criminally flagged.
