### ISSUE TITLE
Error in panic mode

### ISSUE THREAD

**Issue by tetrikx** [Da-Teach/Questor#111]
While using directeve.dll, framework 3.5, in panic mode from capacitor alert, questor warps the ship in space and hangs in panic mode.

Looked in the code and here

// We leave the panicking state once we actually start warping off
                    var station = Cache.Instance.Stations.FirstOrDefault();

the FirstOrDefault() function returns an exception System.ArgumentNullException

How could we resolve this?

**Comment by rixim** [comment]
by fixing your ship configuration.

**Comment by tetrikx** [comment]
Found the solution: replace in panic.cs and StationDestination.cs
WarpToAndDock() with WarpTo()

**Comment by ISeeDEDPpl** [comment]
If this is working for you with experimental please close this issue.
