### ISSUE TITLE
Issue while changing ships from salvager to combat & combat to salvager

### ISSUE THREAD

**Issue by bud131** [Da-Teach/Questor#112]
I am testing questor using a very low SP character, doing lvl1 missions. I have a mission ship called "one" and a salvager called "two" . this is defined on xml.

What i am experiencing since yesterday is that most of the time everything works fine, but often the bot does not switch ships and questor waits cause it is on the wrong ship. If i manually enter the ship questor needs to enter, it picks up and everything works fine.

just to mention that most of the times the bot is moving through ships perfectly so it can go out and salvage. Most of the times i find that the problem occurs while accepting missions when character is on the salvager, but sometimes it cannot switch to salvager and just waits for my input

Anyone else experiencing this issue? have u found a reason? plz advice & thank you

**Comment by bud131** [comment]
I have to turn off salvaging since both normal salvaging with another ship or removing something and placing a salvager on the mission-running ship does not work at all.

I replaced a weapon with a salvager and the bot warps to the bookmark and stands still until i manually target all the wrecks i need salvaged.  After the targeting takes place the salvage goes fine. (i did not test this with a tractor beam since i had only a point for salvaging)

**Comment by bud131** [comment]
Loot after mission does not work unless there is some kind of looting for the mission objective. Then, the bot will loot all wrecks in the current pocket

**Comment by Ganondorf0** [comment]
I can confirm the ship switching has issues. Need to add a check a few seconds after switching ship in arm, to verify that we really switched ship, if not, switch again.

**Comment by bud131** [comment]
or somehow before requesting a mission from agent to get into the mission ship. Having a really hard time today with the salvaging, i had to stop them and have it running missions all the time. Noticed a small issue with declining missions but i'm still checking what's wrong with the blacklist

**Comment by bud131** [comment]
with some help from a friend, i compiled questor to another pc that had everything setup from the start. Bot works perfectly for few hours (switching between ships went perfectly) but afterwards it started having issues switching ships (both from mission-> salvager and salvager->mission) . So i'm trying a different appoarch this weekend and if there are still no replys to this issue i'll delete it

**Comment by ISeeDEDPpl** [comment]
This should be resolved in experimental. Please confirm and close.
