### ISSUE TITLE
Error's Trying to find an acceleration gate.

### ISSUE THREAD

**Issue by Blinker** [Da-Teach/Questor#114]
20:02:43 Combat: Activating weapon [1002689839829] on [Pith Extinguisher][9000000000001562308]
20:31:02 MissionController: Finished Action.ClearPocket
20:31:02 MissionController: Starting Action.Activate [target: Acceleration Gate]
20:31:03 MissionController.Activate: Can't find [Acceleration Gate] to activate! Stopping Questor!
20:31:03 MissionController: Error
20:31:05 Traveler.StationDestination: Destination set to [Somewhere]
20:31:06 Traveler: Setting destination to [Somewhere]
20:31:08 Traveler: Warping to [Stargate (Somewhere)]
20:31:58 Traveler: Jumping to [Somewhere]
20:32:08 Traveler.StationDestination: Warp to and dock at [Station]
20:32:44 Traveler.StationDestination: Dock at [Station]
20:32:59 Traveler.StationDestination: Arrived in station

Then it Stays that way till you restart questor. When restarting though it carries on working fine.

**Comment by Ganondorf0** [comment]
That's just the server not having that mission loaded or something. Maybe stopping questor isn't appropriate, just wait a bit then try again.

**Comment by ISeeDEDPpl** [comment]
Is this still an issue?
