### ISSUE TITLE
[Low Priority]Incorrect item XML

### ISSUE THREAD

**Issue by Phygar** [Da-Teach/Questor#116]
https://github.com/Da-Teach/Questor/blob/master/ValueDump/frmMain.cs#L133 on line 133 prints "Saving InvItems.xml" to the console, but it really saves to "InvTypes.xml"

**Comment by ISeeDEDPpl** [comment]
This has been fixed in my tree for some time now. The Valuedump action in questormanager needed adjustment though, fixed: https://github.com/ISeeDEDPpl/Questor/commit/62afeaca985bb40710e73c1e117ac2d470253431
