### ISSUE TITLE
Bot Hangs During Execute Mission; Dies Without Panic Mode

### ISSUE THREAD

**Issue by jakesmurf** [Da-Teach/Questor#117]
I've had this happen 3-4 times in the past few days.  

The bot will warp to a mission, there doesn't seem to be any correlation between which mission it is, will begin clearpocket, starts shooting at stuff... and then according to the log it won't do anything else afterwards.  Apparently the bot just floats there until the NPC DPS overcomes it's tank and it dies.  It will not attempt to panic at low shield (50%) / armor HP (99%), or anything of that nature.  This only seems to happen if the client is not maximized on top of the stack.  When I remaximize my windows to check my bots, it then immediately realizes upon being maximized that its in a capsule and begins the panic procedures immediately.  

I run a bot each on three different PCs and I've been having this problem with all of them.  I don't know if this is an Innerspace, Questor, or PC problem.  Any input could help.    

07:38:33 Combat: Activating weapon [1005644101125] on [Corpus Archon][9000000000000057902]
07:38:33 Combat: Activating weapon [1005644098726] on [Corpus Archon][9000000000000057902]
20:11:27 Panic: You are in a Capsule, you must have died :(
20:11:27 Combat: No weapons with GroupId [510] found!
20:11:27 MissionController.ClearPocket: Approaching target [Corpum Arch Priest][9000000000000057894]
20:11:27 Combat: Out of Ammo!
20:11:32 Traveler.StationDestination: Destination set to REDACTED
20:11:40 Panic: We've warped off
20:12:24 Panic: Entered a station, lower panic mode

**Comment by ISeeDEDPpl** [comment]
if you want eve to work while minimized you need to have
windowtaskbar on
as a command in the startup of your innerspace profile in order for an onframe events to occur while minimized. This is not a questor bug, this is a design issue within innserspace and EVE and needs to be worked around with "windowtaskbar on"

**Comment by jakesmurf** [comment]
Okay.  Thanks a bunch!  I think I have only been having this problem sporadically because I normally just leave the window in the background, maybe I am just randomly minimizing a client sometimes. I appreciate your help a lot.
