### ISSUE TITLE
dont work parameter r|runtime

### ISSUE THREAD

**Issue by xelj** [Da-Teach/Questor#118]
"r|runtime=", "Quit Questor after {RUNTIME} minutes."
I tried to use  dotnet questor questor -u MyLogin -p MyPass -c "Charname" -r 10
Questor works,  but does not quit after the expiration of the time.

**Comment by GliderPro** [comment]
Did you run a mission or just launch Questor and wait 10 minutes?  Questor does not quit until after your mission is over.  Also, if you never run a mission it will never quit.

**Comment by xelj** [comment]
run mission 8-9hours,autostart on, also tried set 100,400, 500 min

**Comment by ISeeDEDPpl** [comment]
this has been fixed in my tree: 
the help text said minutes, the code added hours. 

I kept both behaviors, if you specify 10 or less it assumes hours. 11 or more it assumes minutes. 
https://github.com/ISeeDEDPpl/Questor/commit/49394f1bfb0e5b93e781e619d65ffb2984d9e8d9

**Comment by xelj** [comment]
thx for help
