### ISSUE TITLE
Questor Shoots wrecks

### ISSUE THREAD

**Issue by intelceleron11** [Da-Teach/Questor#12]
Interestingly, Questor seems to shoot wrecks. Before, it was said to happen only when you don't have a salvager and have the loot all option enabled, but my setup has a salvager and a tractor beam on a CNR. It has been reported the same problem is found on a drake also.

I don't know how to repeat this problem, as other accounts are fine, and a review of the settings XML has shown nothing scary that would jump out at me showing the reason for this glitch. 

It attacks using both drones and launchers, and will both try to salvage and tractor beam while attacking. If I am not mistaken, proper attack protocol dictates that a target painter first is enabled and then launchers enabled, but in this situation it is not necessarily the case. Hopefully this information helps in diagnosing the underlying issue.

**Comment by rixim** [comment]
fixed in https://github.com/Da-Teach/Questor/commit/425af134dff1cb6a8c3fb3ff42a518bb63b9fc6c

**Comment by rixim** [comment]
can you pull from the current master branch and tell me if you still see the problem?
