### ISSUE TITLE
Big problem with panic mode

### ISSUE THREAD

**Issue by ghost** [Da-Teach/Questor#120]
The bot enters panic mode as it should but after warping at the station it will not dock. And after manual dock it will not undock and return to the mission. The log is showing Panic State normal, and wallet balance warning every minute it passes. The compile of the experimental build was done with no errors and 1 warning (dow i need to repair the directEve reference in VisualStudio first).

**Comment by ISeeDEDPpl** [comment]
This has been fixed in my experimental branch for a few weeks now. 

I assume rixim will do another merge shortly.
