### ISSUE TITLE
18:44:53 Traveler: Error [Stargate (Isikemi)] not found, most likely lag waiting 15 seconds.

### ISSUE THREAD

**Issue by alex26-zz** [Da-Teach/Questor#121]
18:44:53 Traveler: Error [Stargate (Isikemi)] not found, most likely lag waiting 15 seconds.

как исправить 
skype   limonalex

**Comment by GliderPro** [comment]
this was fixed a week ago.

**Comment by alex26-zz** [comment]
right now I have this error in the console says that to do with this error

is there someone from the Russian

**Comment by GliderPro** [comment]
Fixed via this commit https://github.com/Da-Teach/Questor/commit/818e85f155e1af9ac4e4b24828724756bb75e1ce

**Comment by alex26-zz** [comment]
все работает спасибо
