### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by vv734** [Da-Teach/Questor#125]
Microsoft (R) Build Engine Version 4.0.30319.1
[Microsoft .NET Framework, Version 4.0.30319.269]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 16.05.2012 17:03:04.
Project "C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj" on node 1 (default targets).
c:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1200,9): warning : The referenced project '....\DirectEve\DirectEve\DirectEve.csproj' does not exist. [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
CoreResGen:
  All outputs are up-to-date.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:DEBUG;TRACE /reference:"C:\Program Files\InnerSpace\Lavish.InnerSpace.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Deployment.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Drawing.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Windows.Forms.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.dll" /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\x86\Debug\QuestorManager.exe /resource:obj\x86\Debug\QuestorManager.MainForm.resources /resource:obj\x86\Debug\QuestorManager.Properties.Resources.resources /target:winexe Actions\Buy.cs Actions\BuyLPI.cs Actions\StateBuyLPI.cs Actions\InvType.cs Actions\ItemCache.cs Actions\ValueDump.cs Actions\StateDrop.cs Actions\StateGrab.cs Actions\StateSell.cs Actions\StateBuy.cs Actions\Grab.cs Actions\Drop.cs Actions\Sell.cs Actions\ValueDumpState.cs ListItems.cs ListViewColumnSorter.cs State.cs Domains\Category.cs Domains\Group.cs Module\BookmarkDestination.cs Common\DirectEve.cs Extensions\DirectEveExtension.cs Common\Logging.cs MainForm.cs MainForm.Designer.cs Module\MissionBookmarkDestination.cs Program.cs Properties\AssemblyInfo.cs Module\SolarSystemDestination.cs Module\StationDestination.cs Module\Traveler.cs Module\TravelerDestination.cs Module\TravelerState.cs Properties\Resources.Designer.cs Properties\Settings.Designer.cs "C:\Users\1\AppData\Local\Temp.NETFramework,Version=v4.0.AssemblyAttributes.cs"
Actions\Buy.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\BuyLPI.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\ItemCache.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\ValueDump.cs(20,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\Grab.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\Drop.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\Sell.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\BookmarkDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(15,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
MainForm.cs(19,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\MissionBookmarkDestination.cs(14,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\SolarSystemDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\StationDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\Traveler.cs(14,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Actions\ItemCache.cs(17,26): error CS0246: The type or namespace name 'DirectItem' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\BookmarkDestination.cs(23,36): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\BookmarkDestination.cs(56,59): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\BookmarkDestination.cs(56,24): error CS0246: The type or namespace name 'DirectLocation' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\BookmarkDestination.cs(73,58): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Common\DirectEve.cs(14,32): error CS0400: The type or namespace name 'DirectEve' could not be found in the global namespace (are you missing an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Common\DirectEve.cs(19,31): error CS0400: The type or namespace name 'DirectEve' could not be found in the global namespace (are you missing an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(28,59): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(28,23): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(41,50): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(59,57): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(59,23): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(70,72): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(70,35): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(80,62): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Extensions\DirectEveExtension.cs(80,23): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
MainForm.cs(45,22): error CS0246: The type or namespace name 'DirectSolarSystem' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
MainForm.cs(46,22): error CS0246: The type or namespace name 'DirectStation' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
MainForm.cs(47,22): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\MissionBookmarkDestination.cs(22,43): error CS0246: The type or namespace name 'DirectAgentMissionBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Module\MissionBookmarkDestination.cs(48,24): error CS0246: The type or namespace name 'DirectAgentMissionBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
Done Building Project "C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj" (default targets) -- FAILED.

Build FAILED.

"C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj" (default target) (1) ->
(ResolveProjectReferences target) -> 
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1200,9): warning : The referenced project '....\DirectEve\DirectEve\DirectEve.csproj' does not exist. [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]

"C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj" (default target) (1) ->
(CoreCompile target) -> 
  Actions\Buy.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\BuyLPI.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\ItemCache.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\ValueDump.cs(20,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\Grab.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\Drop.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\Sell.cs(8,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\BookmarkDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(15,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  MainForm.cs(19,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\MissionBookmarkDestination.cs(14,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\SolarSystemDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\StationDestination.cs(13,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\Traveler.cs(14,11): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Actions\ItemCache.cs(17,26): error CS0246: The type or namespace name 'DirectItem' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\BookmarkDestination.cs(23,36): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\BookmarkDestination.cs(56,59): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\BookmarkDestination.cs(56,24): error CS0246: The type or namespace name 'DirectLocation' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\BookmarkDestination.cs(73,58): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Common\DirectEve.cs(14,32): error CS0400: The type or namespace name 'DirectEve' could not be found in the global namespace (are you missing an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Common\DirectEve.cs(19,31): error CS0400: The type or namespace name 'DirectEve' could not be found in the global namespace (are you missing an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(28,59): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(28,23): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(41,50): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(59,57): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(59,23): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(70,72): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(70,35): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(80,62): error CS0246: The type or namespace name 'DirectEve' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Extensions\DirectEveExtension.cs(80,23): error CS0246: The type or namespace name 'DirectEntity' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  MainForm.cs(45,22): error CS0246: The type or namespace name 'DirectSolarSystem' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  MainForm.cs(46,22): error CS0246: The type or namespace name 'DirectStation' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  MainForm.cs(47,22): error CS0246: The type or namespace name 'DirectBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\MissionBookmarkDestination.cs(22,43): error CS0246: The type or namespace name 'DirectAgentMissionBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]
  Module\MissionBookmarkDestination.cs(48,24): error CS0246: The type or namespace name 'DirectAgentMissionBookmark' could not be found (are you missing a using directive or an assembly reference?) [C:###\evebotec\Da-Teach-Questor-f1ac1f4\QuestorManager\QuestorManager.csproj]

```
1 Warning(s)
35 Error(s)
```

Time Elapsed 00:00:00.31
Done building QuestorManager - see above for any errors - 6 of 7 builds

**Comment by alex26-zz** [comment]
у меня таже проблема кто может помочь
