### ISSUE TITLE
Valuedump error.

### ISSUE THREAD

**Issue by curved** [Da-Teach/Questor#14]
Get this whenever i try to run valuedump at all.This is with the latest version of directeve.

Exception during event execution: System.MissingMethodException: Method not found: 'System.Nullable`1<Int32>
DirectEve.DirectItem.get_Quantity()'.

   at ValueDump.frmMain.OnFrame(Object sender, EventArgs e)

   at (Object , Object , EventArgs )

   at DirectEve.DirectEve.(Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by Bubsan** [comment]
Same problem here. I suppose same error. Didn't log it as I was in a hurry, but I can confirm something's wrong with valuedump.
I switched to rixims' fork (I think, I'm a bit lost with forks and all) and left valuedump to sell.

**Comment by jakesmurf** [comment]
Have you compiled the latest Valuedump?  You need to go back and 'build' Valuedump again after 1.6 Patch

**Comment by curved** [comment]
Ahh i see what you mean, thanks!
