### ISSUE TITLE
Everything out of range

### ISSUE THREAD

**Issue by Blafasl** [Da-Teach/Questor#15]
Hi there,

after a while missioning with an Amarr Battleship with Pulse Laser setup. Wuestor goes into a state where everything is out of range even if i come only 1km onto the target. The Logs show the folllowing:

"23:17:22 MissionController: No mission actions specified, loading default actions
23:17:22 MissionController: Pocket loaded, executing the following actions
23:17:22 MissionController: Action.WaitUntilTargeted [timeout: 15]
23:17:22 MissionController: Action.ClearPocket
23:17:22 MissionController: Action.Done
23:17:34 MissionController.WaitUntilTargeted: We have been targeted!
23:17:34 MissionController: Finished Action.WaitUntilTargeted [timeout: 15]
23:17:34 MissionController: Starting Action.ClearPocket
23:17:36 Combat: Targeting high value target [EoM Crusader][9000000000000285684]{0}
23:17:36 Combat: Targeting high value target [EoM Crusader][9000000000000285679]{1}
23:17:36 MissionController.ClearPocket: Targeting [EoM Crusader][9000000000000285684]
23:17:36 EntityCache: LockTarget is ignored for [EoM Crusader][9000000000000285684], can retarget in [45]
23:17:43 Combat: Targeting high value target [EoM Hydra][9000000000000282678]{2}
23:17:43 Combat: Targeting high value target [EoM Hydra][9000000000000282685]{3}
23:17:44 Combat: Changing [1002641972124] with [Radio L][255]
23:17:44 Combat: Changing [1002641969142] with [Radio L][255]
23:17:44 Combat: Changing [1002641970656] with [Radio L][255]
23:17:44 Combat: Changing [1002641773572] with [Radio L][255]
23:17:44 Combat: Changing [1002641960679] with [Radio L][255]
23:17:44 Combat: Changing [1002641971628] with [Radio L][255]
23:17:44 Combat: Changing [1002641971245] with [Radio L][255]
23:17:44 Combat: Changing [1002641971894] with [Radio L][255]
23:17:46 Combat: Target [EoM Hydra][9000000000000285685] out of range
23:17:46 Combat: Target [EoM Hydra][9000000000000285678] out of range
23:17:46 Combat: Target [EoM Crusader][9000000000000285684] out of range
23:17:46 Combat: Target [EoM Crusader][9000000000000285679] out of range
23:17:49 Combat: Target [EoM Hydra][9000000000000285685] out of range
23:17:49 Combat: Target [EoM Hydra][9000000000000285678] out of range
23:22:05 MissionController.ClearPocket: Approaching target [EoM Crusader][9000000000000285682]
23:22:19 Combat: Target [EoM Death Knight][9000000000000285017] out of range
23:22:22 Combat: Target [EoM Death Knight][9000000000000285017] out of range
23:22:25 Combat: Target [EoM Death Knight][9000000000000285017] out of range
23:22:26 Drones: Engaging drones on [EoM Death Knight][9000000000000285017]
23:22:28 Combat: Target [EoM Death Knight][9000000000000285017] out of range
23:23:09 MissionController.ClearPocket: Approaching target [EoM Crusader][9000000000000285679]
23:23:14 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:17 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:20 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:21 Drones: Engaging drones on [EoM Crusader][9000000000000282682]
23:23:23 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:26 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:29 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:30 MissionController.ClearPocket: Approaching target [EoM Crusader][9000000000000285682]
23:23:32 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:35 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:36 Drones: Engaging drones on [EoM Crusader][9000000000000285682]
23:23:38 Combat: Target [EoM Crusader][9000000000000285682] out of range
23:23:39 Drones: Recalling drones because we have lost shields! [Old: 5,00][New: 2,00]
23:23:46 MissionController.ClearPocket: Approaching target [EoM Crusader][9000000000000285679]
after that it keeps doing the same endlessly"

The odd thing is that somehow Questor sees that the eom crusader inflict a LockTarget event in the EntityCache and after that i cant target anything. Even if i target something manually the "out of range" event shows up and questor about the lock.

The ship is circleling around me a about 25km and my weapons can shoot up to 65km. I tried to reproduce and somehow to debug this but my attempts to reproduce failed as this occurs randomly.

Is there anything i can do to help fix this bug?

**Comment by rixim** [comment]
which version are you using?

**Comment by Blafasl** [comment]
i tried different versions: commit 700df0543fb35897d250,  2b4a43f6a22b80fcca50 and  d42e1a92885c4296d08f
Even in chantlings fork (most recent commit) does this happen.

**Comment by subcool** [comment]
i had this issues too, i noticed that an autopilot course to home base was plotted + 1 or more rats were warp jamming the bot. The bot wouldnt attack them cause they were out of range, even though they were 2.000m away (range is 100+ km).

After manually killing the the 4 jam-capable rats it still would not engage the other rats

**Comment by Blafasl** [comment]
My settings are these:

<ammoTypes>
<ammoType typeId="23105" damageType="EM" range="28300" quantity="16" />
<ammoType typeId="255" damageType="EM" range="75000" quantity="16" />
<ammoType typeId="23105" damageType="Kinetic" range="28300" quantity="16" />
<ammoType typeId="255" damageType="Kinetic" range="75000" quantity="16" />
<ammoType typeId="23105" damageType="Thermal" range="28300" quantity="16" />
<ammoType typeId="255" damageType="Thermal" range="75000" quantity="16" />
<ammoType typeId="23105" damageType="Explosive" range="28300" quantity="16" />
<ammoType typeId="255" damageType="Explosive" range="75000" quantity="16" />
</ammoTypes>

<minimumAmmoCharges>1</minimumAmmoCharges>

<weaponGroupId>53</weaponGroupId>

Imperial Navy Multifrequency L (23105) and Radio L (255).
I can do three or four missions before this bug happens. If i made a 
mistake in my settings i would be grate to see whats wrong.

At 17.06.2011 20:24, xelj wrote:
Check ammo type in settings.xml

**Comment by Blafasl** [comment]
Update:
it seams that this issue is somehow related to DirectEVE as this problem is the same as descriped here: http://forum.thehackerwithin.com/yaf_postsm222_-Problem--How-to-setup-lasers.aspx
With normal crystals the bot runs fine, but if it has to change ammo for the range it aborts every targeting and starts to orbiting around the target. If the problem is really in DirectEve i dont see a way where i can fix it for myself.

**Comment by rixim** [comment]
did you ever fix this issue? This looks like a fitting issue, so i'm closing it.
