### ISSUE TITLE
Invalid XML due to agent switching npc type.

### ISSUE THREAD

**Issue by Serpentstar** [Da-Teach/Questor#16]
I have seen this with Vengeance.  Agent is giving out missions with the NPC faction type changing.  One moment Blood Raider the very next mission Sansha.  I have seen this happening with at least 2 different missions.  Vengence and Recon 1 of 1

Vengeance has different names for Acceleration Gates and Recon 1 of 1 has the nasty NOS monsters in 3rd room for Blood Raiders.  Interesting note is both of these the change is in the Blood Raiders versions.  I have not noticed any other relevant comparison at this time.

My proposal on how to fix...

At the arming stage change to code to be something like this.
look for mission + faction.xml.  (ie Vengeance.Sansha Nation.xml)
if not exist, look for mission.xml (just like it is doing Vengeance.xml)
if not exist look for faction name and load default ammo.

The base is already there.  This means just make xml code for missions that are definitely different than others.
This also allows for customized code to make some missions have less agro by holding off on the triggers until the clearing the rest of the wave.

**Comment by rixim** [comment]
The missions were changed by CCP.
