### ISSUE TITLE
Not loading Multiple damagetypes??

### ISSUE THREAD

**Issue by runkittyrun** [Da-Teach/Questor#17]
Hello

Doing "silence the Informer" Minmatar Level4, the first pocket needs EM, the 2nd and later need Thermal.

I put this in the mission xml

<?xml version="1.0" encoding="utf-8" ?>
<mission>
  <pockets>
    <pocket id="0">
     <damagetype>Thermal</damagetype>
     <damagetype>EM</damagetype>
     <actions>

During the Arm phase, its only loads EM. I'ts not loading both damagetypes.

Any hints?

**Comment by rixim** [comment]
can't read the xml. not sure how to post xml to github :(
