### ISSUE TITLE
[Feature Request] Add missing storylines

### ISSUE THREAD

**Issue by rixim** [Da-Teach/Questor#18]

**Comment by xelj** [comment]
I can share Forgotten Outpost, Innocents in the Crossfire and Patient Zero

**Comment by Zigotta** [comment]
i can shared The Insorum Hijacking, A Persistent Enemy and all transport storylines missions. But original Questor don't support my action-types ;)

**Comment by vercetti** [comment]
Is there a particular reason why storylines are hardcoded and not normal .xml files? There's a bunch of storylines that will probably not get added by developers, but would be easy for anyone to write mission xml file.
Another issue is panic during storyline. Ship docks, lowers panic mode and gives "invalid mission bookmark" error.
