### ISSUE TITLE
Invalid Mission Bookmark

### ISSUE THREAD

**Issue by below0isk** [Da-Teach/Questor#2]
Happens in Panic Mode.
When Panic is started and ship is finally docked Questor will not undock but instead spam the console with "Invaild Mission Bookmark" as it is still docked but tries to warp to a bookmark.

In my specific scene i had a noctis with mwd and the cap ran dry so questor docked and looped the invali mission bookmark traveler bug.

**Comment by rixim** [comment]
Did you resolve the issue that put questor in a panic?

**Comment by below0isk** [comment]
Am 22.05.2011 19:23, schrieb rixim:

> Did you resolve the issue that put questor in a panic?
> 
> oh near lost this mail. yes i fixed it. as usual it was a user error. i 
> put an mwd on the noctis and cap went dry.
> yet the ship should have returned to the bookmark site and start 
> salvaging again but it did not.
> but as da_teach had already said before he knows about this bug in 
> directeve.dll as far as i can remember.

so my workaround was fitting an ab. that fixed it for me. never had any 
panic-and-stay-docked bug again.
