### ISSUE TITLE
[Feature Request] Shoot while traveling to acceleration gate

### ISSUE THREAD

**Issue by rixim** [Da-Teach/Questor#20]

**Comment by xelj** [comment]
+1 
Sometimes EVE starts to slow down the eve, with the FPS monitor shows about 50-60 fps but really very small. After jumping the gates questor begins to jump to the next point during the change of the session, and because of the lag thinks that after loading the system has already passed warp and begin to phase of execute mission. As a result - attempts to fire at Concord and factional militia.

**Comment by rixim** [comment]
Xelj, that's a different issue that is also being addressed.

**Comment by PoorNewb23** [comment]
There is a bug related to this. More precisely, to "move to" action.

Questor will shoot stuff if it's atacked during movement, however, after destination is reached and next action (clearpocket) is issued, bot continues to shoot npcs, but refuses to move/orbit them. 

This makes move-to action a death sentence to every speedtank based ship:(

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/a96a0ecf1754ba272c17b3a814c61087d9a31a6d

**Comment by PoorNewb23** [comment]
Thanks for that one.

2012/2/26 ISeeDEDPpl <
reply@reply.github.com

**Comment by Karr** [comment]
+1 Would def like to see this done.  Golem with no AB/MWD takes some time.  Time is money ;)

Running Experimental of ISeeDEDPpl (90e5e8c0fe27ad7cdb8379a6bcdd8137b4ce368b) dated May 7, 2012.
Verified Golem sits until all ships are dead and slow boats to gate salvaging.

**Comment by GliderPro** [comment]
Why would you want a feature added to Questor when you don't even use this version?  Get ISDP to add it if you want it.

**Comment by ISeeDEDPpl** [comment]
this has already been added. you can use the mission XML actions listed in the example mission XML file:
`
<action name="MoveToBackground">
        parameter name="Target">Acceleration Gate</parameter>
        <parameter name="Distance" value="1000"></parameter>
</action>
<action name="ClearWithinWeaponsRangeOnly"></action>
action name="ClearPocket"></action>
`
to accomplish what you are looking for.

In the output directory you should see: MissionXML_Examples.xml with all the available mission actions.

**Comment by Karr** [comment]
and.. for the answer to this... 

http://forum.thehackerwithin.com/yaf_postsm6060_Dim-s-Modified-ISEEDEDPPL-S-Branch-ONLY-Mission-XML-s.aspx

**Comment by ISeeDEDPpl** [comment]
This issue can be closed when ready.

**Comment by GliderPro** [comment]
I guess that means this issue is resolved.
