### ISSUE TITLE
[Feature Request] Reload Support before using gates.

### ISSUE THREAD

**Issue by Serpentstar** [Da-Teach/Questor#24]
I would like to see if it would be possible to reload when just before activating an acceleration gate.  would be nice to have full ammo at the start of combat and not waiting til you target something and need to shoot.

I do not want it to change ammo based on next pocket.  that would cause unusual activity, in the case of having a panic and you have an ammo change between pockets.  I would rather change once and not for each type on the way back.

**Comment by SystemControl** [comment]
http://forum.thehackerwithin.com/yaf_postsm3046_two-suggestions.aspx#post3046
