### ISSUE TITLE
Disable 3D button not working

### ISSUE THREAD

**Issue by balroken** [Da-Teach/Questor#3]
The disable 3D button isn't working, sucks for me because I like the play other games with eve in the background and it can cause lag issues.

**Comment by balroken** [comment]
Something like evebot's disable 3d would be awesome it reduces computer power use alot. Thanks.

**Comment by rixim** [comment]
Are you running the latest version in the repo?

**Comment by balroken** [comment]
I am running the March 9th version I see there is a disable 3D update in the dll but unsure how to download just that dll as when you click the download button from github it gives me the March 9th Version

**Comment by rixim** [comment]
This issue is fixed in the repo.
