### ISSUE TITLE
GetLocation broken for StationIds

### ISSUE THREAD

**Issue by Weyoun** [Da-Teach/Questor#30]
As title says.

e.g.

DirectEve.Navigation.GetLocation(60001495);

Will not be valid. This Id is "Iivinen IV - Moon 8 - Rapid Assembly Factory"

**Comment by rixim** [comment]
did you run updateinvtypes?

**Comment by Weyoun** [comment]
No, because GetLocation was never dependant on invTypes. ;)

**Comment by rixim** [comment]
what was it dependent on?

**Comment by Weyoun** [comment]
Maybe the client itself. I never used questor I just used DirectEve so I'm pretty sure its not dependant on any questor specific stuff.
As far as I am away, Questor doesn't use GetLocation() with station IDs where I am. As of last patch it is broken i.e. it will return null.
Using GetLocation() with a solarsystem id is still working.

**Comment by Ganondorf0** [comment]
You can work around this issue by using bookmarks, they will have the id stored.
