### ISSUE TITLE
Gun Deactivation Generates Exception

### ISSUE THREAD

**Issue by Inevitable** [Da-Teach/Questor#33]
The exception is as follows:

C:\Program Files (x86)\CCP\EVE#NACHINE.2011.07.02.ERRORS.lbw

51582   2011.07.02  EXCEPTION 10 logged at  07/02/2011 Unhandled exception in TaskletExt object at 28c73638, abps=1001, ctxt='<NO CONTEXT>^<bound method ModuleButton.DeactivateEffect of xtriui.ModuleButton object at (snip)b080880, name=ModuleButton, destroyed=Fa

C:\Program Files (x86)\CCP\EVE#MACHINE.2011.07.ERRORS.lbw

51603   2011.07.02  UserError: [EffectStillActive.notify] None - The Mega Pulse Laser II cannot be manually deactivated in the middle of an operation, it will deactivate without repeating in 0.0 seconds (its activation duration is 4.6 seconds). {'duration': 4.611549630390

Questor seems to occasionally throw this exception when a target explodes and guns are still in a green state.  I was unable to reproduce this manually while attempting to disable my guns, both via hotkey and clicking under the same conditions as questor produces it.

This was produced with hash acc072b

**Comment by Ganondorf0** [comment]
I know, those are yellow exceptions, just normal error messages. I think you can replicate it manually by spamming activation on the weapon while the target explodes, or just before it. I'm not sure they were there before the last patches. There are 2 possible fixes, one might work and isn't too great, adding more delays to the weapon activation. The other would work but idk if/when we can do that, check the cycle times of all active modules so we never activate or deactivate a module during its cycle.

**Comment by Ganondorf0** [comment]
After some testing and going through the code, this is a simple one. The deactivate method is missing a isdeactivating test, that will solve it. When i get time i'll push the fix to github.

**Comment by Ganondorf0** [comment]
DaTeach pushed a fix last week that addressed this.
