### ISSUE TITLE
Panic from cap to low on "Gotobase"

### ISSUE THREAD

**Issue by Pluckyduck** [Da-Teach/Questor#37]
if the cap get below the threshold when warping back to base after mission is completed the bot goes into panic.  After the panic is cleared then questor return to empty mission.

**Comment by rixim** [comment]
This is a known issue. If anything it's a problem with your fitting and/or panic. ...but fixing panic is a bit of a quagmire and won't happen pre-V2.

**Comment by Da-Teach** [comment]
On a side note, Cap is no longer a panic-check when Questor is not in a mission.
