### ISSUE TITLE
 MoveTo and speedtank

### ISSUE THREAD

**Issue by xelj** [Da-Teach/Questor#38]
After MoveTo action questor dont use speedtank

**Comment by PoorNewb23** [comment]
I can confirm the issue.

**Comment by ghost** [comment]
Do you have an example mission I will take a look?

**Comment by bbday** [comment]
in missioncontroller.cs
find: "private void movetoaction"
find: "if (closest.distance < 2500"

if (Cache.Instance.Approaching != null)
                {
                    closest.Orbit(2000); //add , when the item is less 2500m orbit on 2000m to it
                    // disabled Cache.Instance.DirectEve.ExecuteCommand(DirectCmd.CmdStopShip);
                    Cache.Instance.Approaching = null;
                }
