### ISSUE TITLE
Materials for war preparation - not enough reasonably priced kernite

### ISSUE THREAD

**Issue by vercetti** [Da-Teach/Questor#39]
Switched form master branch. Now the bot just fails buying it at all eg. Kernite in station at 2% below average. Old version bought it without much fuss, iirc up to 100% above avg or something. What part of code is responsible for this?

**Comment by xelj** [comment]
Once there was this bug, but it turned out that the problem was in InvTypes.xml, there was no point medianbuy, restart UpdateInvTypes.exe helped.

**Comment by Da-Teach** [comment]
The bot indeed checks the medianbuy price in InvTypes.xml, if there's no price (or an invalid price) then the bot will not buy kernite since it'll be deemed 'too expensive'.
