### ISSUE TITLE
GoToBM to nowhere

### ISSUE THREAD

**Issue by iMutant** [Da-Teach/Questor#4]
Happened many times. When I trevel to Asrios or from Asrios (Kador) on second jump it start start looping destination. Where u go, and from. Does there any console command to stop gotobm? and why this happens?

**Comment by iMutant** [comment]
Sorry, there is no GoToBM in your fork, close issue.

**Comment by rixim** [comment]
"dotnet -unload gotobm" should stop it.

can you paste the output from the console?

**Comment by iMutant** [comment]
Whole day was trying to catch this bug, but all works clear.
After warp, it didn't jump in and change destination with 1s interval.
Traveler: Setting destination to [Aphend]
Traveler: Setting destination to [Asrios]
Traveler: Setting destination to [Aphend]
and so on.
And first time it was truing to set destination to Constellation name "Qermi", not system name "Asrios". and start looping "Aphend" and "Qermi"

**Comment by rixim** [comment]
I am going to assume there is something wrong with your bookmark, good luck.
