### ISSUE TITLE
DirectContainer.Add() locks Items when put into secure container

### ISSUE THREAD

**Issue by BassMonkey** [Da-Teach/Questor#40]
I try to add the ability to use station containers instead of corp hangars. There should be few who are lucky to get a corp hangar at their missioning base.

Everything works fine except that the DirectContainer.Add() method seems to lock all items after moving them into a secure container. I think, this should be an issue with DirectEve.

Details can be found in this thread: http://forum.thehackerwithin.com/yaf_postst472_DirectContainer-OpenContainer.aspx

**Comment by GliderPro** [comment]
I'm pretty sure this is how those containers work.  Have you tried dragging an item into the container manually?

**Comment by BassMonkey** [comment]
I know how secure containers work and already set the container to "Unlock". It is definitely a bug. Manually dragging them to the container works fine.

**Comment by Da-Teach** [comment]
Putting an item into a container 'unlocked' requires additional parameters in the python-call.

**Comment by BassMonkey** [comment]
Is it possible to add this command to the Add() function?

If you are already working at the containers, it would also be helpful, if you added a function, to open the container window of a station-container. If there are only few station containers, all containers are loaded to the local memory. However if there are too many station containers, some containers are only loaded, when you open their window. (I will open a new issue for this.)
