### ISSUE TITLE
Salvaging somebody's bookmarks

### ISSUE THREAD

**Issue by iMutant** [Da-Teach/Questor#41]
I made my first's char mission by second char, and created salvage bookmarks was given to third. So he fly to salvage by "start after mission salvaging" command. But didn't salvage. After warping to pocket he sad: "We done with this pocket" and warps to next bookmark.
Why?
And how to fix it?
Maybe should abandon wrecks first?

**Comment by BassMonkey** [comment]
Are you in the same corp? Questor will only touch wrecks, that belong to you or your corp. So abandoning will not help either. And even if you would implement an "abandoned check", as far as I know there is no command in DirectEve to abandon wrecks.
So create a corp and put both chars into it.
