### ISSUE TITLE
[DirectEve bug] DirectCmd.CmdLogOff

### ISSUE THREAD

**Issue by Orkanoid** [Da-Teach/Questor#42]
Dunno why was my previous issue closed without verifying that it is fixed... because it is not fixed, at least not for version DirectEve version of 22 Jun. So, reposting.

Subj is bugged. It works, but after it's done, 2 (and sometimes even 3) EVE windows reopen instead of one. Each of them starts with the same login sequence, so they just keep stealing the same character one from another (which, again, ruins the whole point of auto-relogin). Indeed, you have to have a login sequence to reproduce it.

The bug never appears when manually pressing Log Off button, plus it never appears at disconnect (in both cases a single new EVE window opens for each "dead" one), so it is actually a DirectEve bug. The bug never appears when there is enough system resources (i.e. when you run just one window at decent comp). To reproduce it, you have to launch a EVE+Questor instance per every 500Mb of your RAM, minus memory occupied by Windows. For me, it appears every time when I let either of my 6 toons (at Win7 64bit machine with 4Gb of RAM) to log off and reconnect automatically (as opposed to logging them off manually, as I do it while the bug is not fixed).

**Comment by BassMonkey** [comment]
I noticed this a few days ago but only while I was debugging. I can imagine that questor will send the LogOff-command multiple times if the eve process does not close fast enough. Maybe you could try to add a delay so that the logoff-command will not be send again for a few seconds after sent once.

**Comment by Orkanoid** [comment]
Yes! You've got a solid point: with many EVE windows open and RAM almost used up, it takes like half a minute to close a window. I can easily imagine DirectEVE sending multiple logoff commands. Really, maybe a timer of, say, 30 seconds should be added for it?
