### ISSUE TITLE
[DirectEve feature request] DirectEve.ActiveShip.Velocity property

### ISSUE THREAD

**Issue by Orkanoid** [Da-Teach/Questor#43]
If would be way safer to bot if DirectEve.ActiveShip had a Speed/Velocity property, to return your current speed. For example, it would be useful to check if last warp attempt was successful. Atm, without any collision avoidance, a toon sometimes bumps into a collidable object while warping, and either gets nuked, or just stays there for ages. Its speed varies from close to zero to some really low value, like a 1/4 of max velocity - such condition would be a flag of collision.

**Comment by Da-Teach** [comment]
You could just look up the entity of your ship and check the velocity of that entity, that should work.
