### ISSUE TITLE
Problem when being Target Range Damped

### ISSUE THREAD

**Issue by Assail** [Da-Teach/Questor#44]
The scenario is you are target damped down to like 15k targeting range.

in missioncontroller.cs at line 181 you approach at weapon range *.8, this makes my ship stay at around 40k from the target.

The fix it to use the range variable that's already in the function.

IE line 181                         target.Approach((int) (range \* 0.8d));

**Comment by rixim** [comment]
did you push this fix already?

**Comment by ghost** [comment]
No, I don't think i have rights to do so.

**Comment by rixim** [comment]
put it in your repo then make a pull request to experimental and I will put it in. there some way to attach that pull request to this thread, i don't know how.
