### ISSUE TITLE
[urgent] DirectEve update needed for Incarna 1.1

### ISSUE THREAD

**Issue by pfruh** [Da-Teach/Questor#46]
Seems like DirectEve needs to be updated, as the following code is causing the problem because the agent object is null.

Questor.cs:

<pre>
var agent = Cache.Instance.DirectEve.GetAgentByName(Settings.Instance.AgentName);
if (agent == null || !agent.IsValid)
{
       Logging.Log("Settings: Unable to locate agent [" + Settings.Instance.AgentName + "]");
       ValidSettings = false;
}
</pre>

**Comment by pfruh** [comment]
I already added some debugging output, its not the "agent.IsValid" whats making problems, its DirectEve bugging (agent is null).

**Comment by rixim** [comment]
This will be taken care of as all patches are. Join the IRC channel if it is really that urgent.
