### ISSUE TITLE
Out of ammo

### ISSUE THREAD

**Issue by Crypt** [Da-Teach/Questor#49]
If out of ammo Cache.WeaponRange return 0. 
In Combat.TargetCombatants  "var maxRange = Math.Min(...." will always be equal to 0 and targets also will be 0.
Checking ammo is during activation of weapons, if targets 0 weapons never be activated.

The simplest option to fix it in Cache.WeaponRange replace 
if (ammo.Count() == 0)
                    return 0;
on 
if (ammo.Count() == 0)
                    return System.Convert.ToInt32(Cache.Instance.DirectEve.ActiveShip.MaxTargetRange);

**Comment by rixim** [comment]
Post the full code/patch/diff or send a pull request, thank you.

**Comment by rixim** [comment]
It's merged into experimental, I should not have responded to the pull request, sorry for the confusion.
