### ISSUE TITLE
May 31 patch DirectEve issues

### ISSUE THREAD

**Issue by Orkanoid** [Da-Teach/Questor#5]
1) DirectLoginSlot.Activate is broken. It just doesn't work, which ruins the whole point of scheduling.
1.1) While we are at it, DirectLoginSlot.CharName needs to be filtered of html stuff (can be done in Questor a well, though).

2) DirectCmd.CmdLogOff is bugged. It works, but after it's done, 2 (and sometimes even 3) EVE windows reopen instead of one. Each of them start with the same login sequence, so they just keep stealing the same character one from another (which, again, ruins the whole point of auto-relogin). Indeed, you have to have a login sequence to reproduce it.

3) DirectContainer.IsReady is bugged: it returns false for your shipo cargo no matter if its window is open or not + no matter how long do you wait. To reproduce it, you have to leave and reenter a station with cargo window open: then it goes stuck waiting for cargo to "be ready". Can be avoided by such hack as closing cargo window before entering a station, but this hack has to be added in a lot of pieces of Questor code.

**Comment by rixim** [comment]
are you still experiencing these bugs?

**Comment by Orkanoid** [comment]
I didn't have any time to test the new lib. Let me ask you a counter-question: did you (or DT) fix these bugs (second of them, in particular - as it is the hardest to reproduce)?
