### ISSUE TITLE
Unable to locate agent

### ISSUE THREAD

**Issue by Rolock** [Da-Teach/Questor#50]
After 1.1 patch, I have been getting the "Unable to locate agent" error when starting questor.
From the thread I had on the forums:
The version it uses (.NET 3.5) is included in windows 7, here is the compile result:
http://i.imgur.com/CIoxC.png 

I have deleted the contents of the .NET folder, then placed the new folders and files into it, I then copied the files from \bin\debug\ to the .NET folder - I have tried with just those files, and with all the files from \bin\debug\ from each folder, same effect

And here is the error that I am given after typing "dotnet questor"
http://i.imgur.com/ZRao0.png 

Things I have tried:
Getting the master build, using the command prompt to compile
Getting the master build, and compile.bat from experimental
Having a friend send me his .NET folder to replace mine
Copying only the contents of questor\bin\debug\ to the .net folder
Copying all of the contents from *\bin\debug\ to the .net folder
Changing the agent to the level 3 one (same error, different name)

**Comment by rixim** [comment]
If you can't compile, we can't help. Sorry.

**Comment by Rolock** [comment]
I'm not entirely sure what you mean by that, I posted a picture of the compile result showing no warnings or errors, it compiled correctly.

**Comment by rixim** [comment]
you seem to be using the wrong version of the code.

**Comment by Rolock** [comment]
I've downloaded and compiled both master and experimental as of a few hours ago, the error is the same.  I have check my .net version, it is 4.0

**Comment by Ganondorf0** [comment]
Look for an old directeve.dll, if it's for example in the innerspace folder, it will have priority over the one in .net programs. It's really an issue with you executing still the old version and not an issue with questor itself.

**Comment by Rolock** [comment]
I ended up completely uninstalling and reinstalling innerspace, it worked after that, I recommend telling others to do the same.
