### ISSUE TITLE
Issue with drone stats in dextorious test fork

### ISSUE THREAD

**Issue by drokk99** [Da-Teach/Questor#51]
I had the fitting manager taking care of drone reloading, using different drone for each fitting, so I had set the drone type in the char.xml to 0. This causes an exception to be thrown constantly when counting the drones, not allowing you to actually complete the mission.

**Comment by rixim** [comment]
We only support Da-Teach Questor. if the bug is in that, file against that. Try talking to dextorious in the IRC channel.
