### ISSUE TITLE
Problem with running crystals on the Paladin:

### ISSUE THREAD

**Issue by Pluckyduck** [Da-Teach/Questor#55]
tested 6 Sep Main Build

  Would not even load crystals that were used

Test on 7 Sep Exp Build:

 Questor works like a charm until rats are equal to or greater than 60km from ship.  At this point questor will finish salvaging everything in reach

 and will not move toward rats or any wrecks out side of range of tractor beams.

 I have tried to close cargo and questor will reopen it and then "Combat: Target [rat][long number] out of range". then followed by "MissionController.ClearPocket: Approaching target [rat][really long number]" at this point the ship will approach and then stop the ship.

 for this bug to be reproduced:

  T2/faction crystals
  rats out of crystals set range

 With t1 crystals, i have not had  this problem.

 I am not been able to isolate what causes the bug.

**Comment by Pluckyduck** [comment]
updated

I have it working with Faction ammo ONLY up to the point where i have no more packaged crystal and still fireing when i run out of package crystal

With T1 cystals, MissionController.ClearPocket: Approaching targe [rat][longnumber]

and will move within range and lock and start shooting again

Bug only happens with faction/t2 crystals?

# 

```
<ammoType typeId="23117" damageType="EM"        range="48000" quantity="10" />
<ammoType typeId="23111" damageType="EM"        range="34000" quantity="10" />
<ammoType typeId="23105" damageType="EM"        range="23000" quantity="10" />
<ammoType typeId="23117" damageType="Kinetic"   range="48000" quantity="10" />
<ammoType typeId="23111" damageType="Kinetic"   range="34000" quantity="10" />
<ammoType typeId="23105" damageType="Kinetic"   range="23000" quantity="10" />
<ammoType typeId="23117" damageType="Thermal"   range="48000" quantity="10" />
<ammoType typeId="23111" damageType="Thermal"   range="34000" quantity="10" />
<ammoType typeId="23105" damageType="Thermal"   range="23000" quantity="10" />
<ammoType typeId="23117" damageType="Explosive" range="48000" quantity="10" />
<ammoType typeId="23111" damageType="Explosive" range="34000" quantity="10" />
<ammoType typeId="23105" damageType="Explosive" range="23000" quantity="10" />
```

  </ammoTypes>

#

**Comment by ghost** [comment]
Post ammo part of your config

**Comment by Pluckyduck** [comment]
thanks to assail,

minimumAmmoCharges>-1</minimumAmmoCharges

seems to have fixed the issue.
