### ISSUE TITLE
Agent Decline Timer Issue

### ISSUE THREAD

**Issue by ghost** [Da-Teach/Questor#56]
I have my  minStandings 6.0 set and waitDecline true activated as well. Questor has no issue seeing this. However, questor is missing the decimal point somehow when it reads the actual standings in game.

Example follows:
AgentInteraction: Saying [Request Mission]
AgentInteraction: Waiting for mission
AgentInteraction: Mission enemy faction: Amarr Empire
AgentInteraction: Declining blacklisted faction mission
AgentInteraction: Agent decline timer detected. Current standings: 58. Minimum standings: 6
AgentInteraction: Current standings above minimum.  Declining mission.
AgentInteraction: Saying [Decline]
AgentInteraction: Replying to agent
AgentInteraction: Saying [Request Mission]
AgentInteraction: Waiting for mission

At the time it declined the mission I observed a standing of 5.8 Agent standing, which was my highest effective standing at the time.

Not sure if this is a simple fix or not. I am going to try and set my minStandings to 60 and see if that works for now.

Experimental Build

**Comment by Rx2** [comment]
I can confirm this. In order to for it to have a standing decline at 8.0, you will have to change your setting to 80.

**Comment by Rx2** [comment]
Line 344: AgentInteraction.cs

```
                        var standingValue = standingMatch.Groups["standing"].Value;
                        standingValue = standingValue.Replace('.', ','); // necessary for systems w/ comma-delimited number formatting
                        standings = float.Parse(standingValue);
                        Logging.Log("AgentInteraction: Agent decline timer detected. Current standings: " + standings + ". Minimum standings: " + minStandings);
                    }
                   if (standings <= minStandings)
                    {
```

I don't know much about C# or programming in general, but can it be because we're replacing the decimal with a comma on a floating point number? Wouldn't the output be something like this?:

8.0  // minStanding setting
8,0 // converted number to make it compatible
80 // ends up being the same value as 8,0

Am I wrong about this? 

Hopefully someone can clarify, I might learn something :)

**Comment by rixim** [comment]
This is a known internationalization issue, there are solutions in other parts of the code... look around and I will push a fix if one is provided.
