### ISSUE TITLE
Invalid bookmark loop in questorstate.gotomission

### ISSUE THREAD

**Issue by FeroxRev** [Da-Teach/Questor#71]
If questor enters gotomission state without really accepting a mission(due to a mission m3 acceptence popup or any other) it enters a loop executing cache.instance.getmissionbookmark every 2-3 seconds.

After the following line in questor.cs:

 _traveler.Destination = new MissionBookmarkDestination(Cache.Instance.GetMissionBookmark(Cache.Instance.AgentId, "Encounter"));

Add:
                         if(Cache.Instance.GetMissionBookmark(Cache.Instance.AgentId, "Encounter") == null)
                        {
                            Logging.Log("Invalid bookmark loop! Mission Controller: Error");
                            State = QuestorState.Error;
                        }
Another solution is adding a && (Cache.Instance.GetMissionBookmark(Cache.Instance.AgentId, "Encounter") == null) to the above IF procedure and write an else to go to the errorstate, no idea what's better.

Rixim asked me to post the code here, if this format is totally wrong or simply the code is not right, please tell me :)

**Comment by FeroxRev** [comment]
Updated thread working now

**Comment by Ganondorf0** [comment]
Hello, i think 
State = QuestorState.UnloadLoot;
is better. So it doesn't stop but unloads loot and starts the mission.

**Comment by FeroxRev** [comment]
Good one, but issue is something prevents accepting the mission, so you want to stop questor and manually check whats wrong
