### ISSUE TITLE
[Feature Request] Track Ammo Cost or Consumption in Statistics

### ISSUE THREAD

**Issue by ghost** [Da-Teach/Questor#74]
It would be nice to have the new statistic program include the cost of ammo in its output. This in my opinion would provide the ultimate in complete analysis for the efficiency of questor.

**Comment by CaptObvious** [comment]
This shouldn't be too hard to do, all we'd need to do is count the ammo in the hold and the ammo left in the guns and compare that to the amount of ammo loaded into the cargo when the mission was accepted.  The cost can then be worked out in the same way as the loot is.
