### ISSUE TITLE
Jettisoning ammo when out of cargo space for mission item

### ISSUE THREAD

**Issue by CaptObvious** [Da-Teach/Questor#78]
10:03:41 Salvage: Opening container [Cargo Container]
10:03:46 Salvage: Jettisoning [1] items to make room for the more valuable loot
10:03:51 Salvage: Looting container [Cargo Container], [1] valuable items
10:03:51 Salvage: Opening container [Cargo Container]
10:03:52 MissionController.Loot: We are done looting
10:03:52 MissionController: Finished Action.Loot [target: Cargo Container] [item: Prisoners]

This dumps the whole stack of ammo, rather than just enough to fit the mission item in - this time there wasn't much there, but with T2 ammo that could be quite expensive.

**Comment by SystemControl** [comment]
then pick it up in salvage

**Comment by CaptObvious** [comment]
If I pick the ammo up in salvage it puts it back into my loot tab in the corp hangar rather than ammo, so I end up with a large stack of ammo not being able to be used until I manually move it back.

**Comment by ISeeDEDPpl** [comment]
This is no longer an issue in experimental... unloadloot will put all ammo in your ammo hangar (local items hangar or corpAmmoHangar)
