### ISSUE TITLE
TransactionDataDelivery bug

### ISSUE THREAD

**Issue by xelj** [Da-Teach/Questor#8]
Use https://github.com/Da-Teach/Questor from 31 may

Questor is not checked the mission before going to the agent. Pick-up station was lowsec, questor declined it after arriving to the agent, and then stopped.
## log:

Questor: Random mission start delay of [0] seconds
Questor: Storyline detected, doing storyline.
Storyline: Going to do [Transaction Data Delivery] for agent [xxxxxx]
TransactionDataDelivery: Switching to shuttle
Traveler.StationDestination: Destination set to [xxxxxx]
Traveler: Setting destination to [xxxxxx]
Traveler: Warping to [Stargate (xxxxxx)]
Traveler: Jumping to [xxxxxx]
Traveler: Warping to [Stargate (xxxxxx)]
Traveler: Jumping to [xxxxxx]
Traveler.StationDestination: Warp to and dock at [xxxxxx]
Traveler.StationDestination: Arrived in station
AgentInteraction: Start conversation [Start Mission]
AgentInteraction: Waiting for conversation
AgentInteraction: Replying to agent
AgentInteraction: Waiting for mission
AgentInteraction: Faction fitting Default
AgentInteraction: Declining low-sec mission
AgentInteraction: Saying [Decline]
AgentInteraction: Replying to agent

---

And after that questor stopped

**Comment by rixim** [comment]
I think this bug is fixed here: https://github.com/rixim/Questor please test.

**Comment by rixim** [comment]
I can only assume this works.
