### ISSUE TITLE
Questor.Statistic Date format

### ISSUE THREAD

**Issue by below0isk** [Da-Teach/Questor#80]
questor statistics in the day/month tab. especially month tab
day and month are interchanged. 
MM/DD/YYYY -> should be DD/MM/YYYY on european systems.

**Comment by SystemControl** [comment]
that format comes up on the log?
copie a linea

**Comment by below0isk** [comment]
13/10/2011 HH:MM:SS;Mission title one;xxxxxxxxxxxxxxxxx   <- dd and mm interchanged by me manually
10/13/2011 HH:MM:SS;Mission title two;xxxxxxxxxxxxxxxxxxxx   <-  the way questor.statistics writes to the log file.

**Comment by SystemControl** [comment]
https://github.com/SystemControl/Questor/commit/ae1b88697b492e39ce1a9854a44471a7a0f287b9

var line = string.Format("{0:dd/MM/yyyy HH:mm:ss}", DateTime.Now) + ";";
