### ISSUE TITLE
Reloading loop with two ammp types in cargo

### ISSUE THREAD

**Issue by below0isk** [Da-Teach/Questor#85]
Situation:
Two ammo types in cargohold.
The first stack of ammo type 1 is nearly depleted and launchers are only partially reloaded but above <minimumAmmoCharges> value.
Questor does not attack current but swtiches to the secondary ammo type.
After reloading with ammo type 2 questor tries to reload with ammo type 2 again.
After second reload with ammo type 2 questor reloads ammo type 1.
WHILE reloading ammo type 2 questor tries to activate weapon on current target.
After successful reload of ammo type 1 questor does NOT attack current target.
The launchers are only partially loaded with ammo type 1 and questor reloads ammo type 2.
hence and repeat.

Log:
hh:00:18 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:01:28 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Heavy Missile][209]
hh:02:52 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Heavy Missile][209]
hh:02:16 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Fury Heavy Missile][2629]
hh:02:19 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:02:22 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:02:25 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:02:40 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Heavy Missile][209]
hh:03:04 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Fury Heavy Missile][2629]
hh:03:07 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:03:10 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:03:13 Combat: Activating weapon [Heavy Missile Launcher II ID] on [Spider Drone II][Spider Drone II ID]
hh:03:28 Combat: Changing [Heavy Missile Launcher II ID] with [Scourge Heavy Missile][209]

---

(fyi: replaced the IDs. not sure about what the weapon ID says at it is not in the invtypes.xml. is this a retraceable id ??)

**Comment by rixim** [comment]
User Error, raise minimumAmmoCharges. to the minimum required to fully load all the weapons on your ship.

**Comment by below0isk** [comment]
i had like 3000 charges of ammo type 1 and 3000 of ammo type 2. thought questor would change to type2 if type1 is depleted. or is this just for 2 different damage types for different pockets ?

**Comment by ghost** [comment]
Different ranges/damage types
