### ISSUE TITLE
Storylines not detected

### ISSUE THREAD

**Issue by Bubsan** [Da-Teach/Questor#9]
Using latest Da-Teach/Questor version.
Running 4 bots, 2 machines (3+1).
Yesterday 2 bots were detecting and doing storylines and 2 weren't. Today at least 1 is not detecting and doing them. I was waiting for Materials for war on all of them to mark if given bot is detecting them.
Charname.xml files are identical, except for name of the ship and weapon IDs.

Also, 2 of them when accepted first mission upon launch returned following in the console and continued as if nothing happened:

Traveler.BookmarkDestination: We're docked at the wrong station, undocking

One of those 2 that returned the line from above is not detecting storylines... Just mentioning if it might be connected somehow...

**Comment by xelj** [comment]
Try remove comment in Storyline.cs
// _storylines.Add("Materials For War Preparation", new MaterialsForWarPreparation());

**Comment by Bubsan** [comment]
Will this remove ability to do only "materials for war preparation" storyline? That's probably the only mission that I want them to do.

I have some bots doing storylines, others don't. Questor version is the same, charname.xml identical.

**Comment by xelj** [comment]
Hm, I too have problem with storylines

23:28:18 Questor: Random mission start delay of [0] seconds
23:28:21 Questor: Storyline detected, doing storyline.
23:28:23 Questor: We have completed the storyline, returning to base

but really mission not completed
