### ISSUE TITLE
Error before undocking.

### ISSUE THREAD

**Issue by Bubsan** [Da-Teach/Questor#94]
So, just before undocking I sometimes get this error:
Questor console says:
...
01:28:21 Traveler.MissionBookmarkDestination: Destination set to mission bookmark [Encounter (Deadspace) - XXX]
01:28:23 Traveler: Set destination to [xxx]

and Eve says in window with OK button:

Slow down!
You can't do this quite so fast. Please wait Less than one second before trying again.

Any help?!

**Comment by rface** [comment]
That's the exact same error I reported before, except I actually bothered to watch to see when it showed up, which was at unloading/stacking and not traveling.

**Comment by Bubsan** [comment]
When did you notice this error? Before Crucible expansion or after?
How did you deal with it? Did you fix it?

**Comment by Bubsan** [comment]
OK, sorry, just now I noticed your report right beneath mine. Somehow I kept overlooking it and never concentrated on the one right below mine :(
I think the message pops up at the same time as in your case, I just didn't pay attention during whole docking period. I will test it when I get home.

**Comment by Bubsan** [comment]
error is fixed in latest master version.
