### ISSUE TITLE
Salvaging but not looting - loop

### ISSUE THREAD

**Issue by below0isk** [Da-Teach/Questor#96]
in: after mission salvage
with: salvage ship - noctis
ver: crucial 1.0.1 #1 latest experimental questor. no compile errors.

while in salvage mode, wrecks are successfully salvaged but are not getting looted.
after all wrecks were tractor beamed and salvaged, questor cycles through all containers, opens them but does not loot anything. remains on the first bookmark for ever.

issue is reproducible. 

Truncated Log from a single wreck :

Salvage: Locking [xx Wreck][wreckID]
Salvage: Activating tractorbeam [tractorbeamID] on [xx Wreck][wreckID]
Salvage: Opening container [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Activating salvager [salvagerID] on [xx Wreck][wreckID]
Salvage: Opening container [Cargo Container][containerID]
Salvage: Opening container [Cargo Container][containerID]
Salvage: Opening container [Cargo Container][containerID]
Salvage: Opening container [Cargo Container][containerID]
Salvage: Opening container [Cargo Container][containerID]

**Comment by vercetti** [comment]
Same here, but during the mission. Will not loot anything ever, not even mission items.

**Comment by rixim** [comment]
Fixed in: 5c551eed83257e22ce4ed6febdf086cb41548f08
